# Generated by Django 3.0.3 on 2020-03-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x',
            new_name='x_c',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y',
            new_name='y_c',
        ),
    ]
